### ISSUE TITLE
Uniformity of the names of this add-on

### ISSUE THREAD

**Issue by Korb** [kbuffington/foo_enhanced_playcount#7]
1. Enhanced playback statistics
2. Enhanced Playback Statistics
3. Enhanced Playcount
4. foo_enhanced_playcount

This addition to foobar2000 is called differently in different places. I propose to choose and indicate the same name everywhere, in order to avoid ambiguity.

**Comment by kbuffington** [comment]
So this component attempted to follow the model Peter already established with foo_playcount => "Playback Statistics"

You are correct though, in several places in the UI I was listing "Enhanced Playcount" instead of "Enhanced Playback Statistics". I've fixed that. Documentation is probably all over the place still though.
